# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_by',
            new_name='news_created_by',
        ),
    ]
