# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161026_1513'),
        ('tasks', '0003_auto_20161019_1410'),
    ]

    operations = [
    ]
